"""FastAPI app factory — FROZEN (Phase 0 seam #4).

Do NOT edit this file in Phase 1/2. All base routers are already included (stub 501).
Each vertical implements its OWN router file; cross-cutting extensions attach via
`app/extensions.py` registries. main.py only assembles.
"""
from __future__ import annotations

import base64
import os
os.environ["CREWAI_DISABLE_TELEMETRY"] = "true"
os.environ["CREWAI_TRACING_ENABLED"] = "false"
os.environ["OTEL_EXPORTER_OTLP_TRACES_TIMEOUT"] = "1"
os.environ["OTEL_EXPORTER_OTLP_TIMEOUT"] = "1"

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

from contextlib import asynccontextmanager
import httpx
import requests
from fastapi import FastAPI
from langfuse import Langfuse, __version__ as langfuse_version
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter

from app import extensions
from core.logging import configure_logging, get_logger
from core.settings import get_settings, sync_langfuse_env


# --- Base routers (frozen include list; owners edit only their own router file) ---
from routes import (
    customer_agent_routes,
    event_routes,
    health,
    map_routes,
    merchant_agent_routes,
    merchant_profile_routes,
    merchant_search_routes,
    trace_routes,
    user_routes,
)

logger = get_logger(__name__)

_BASE_ROUTERS = [
    health.router,
    merchant_search_routes.router,
    merchant_profile_routes.router,
    customer_agent_routes.router,
    merchant_agent_routes.router,
    user_routes.router,
    event_routes.router,
    map_routes.router,
    trace_routes.router,
]

def create_session():
    session = requests.Session()
    session.verify = False
    original_request = session.request

    def request(method, url, **kwargs):
        kwargs["verify"] = False
        return original_request(method, url, **kwargs)

    session.request = request
    return session


def initialize_langfuse():
    settings = get_settings()
    sync_langfuse_env(settings)

    insecure_ssl = (
        os.getenv("LANGFUSE_INSECURE_SSL", "false").lower() == "true"
    )

    client_options = {
        "httpx_client": httpx.Client(verify=not insecure_ssl),
    }
    if insecure_ssl:
        public_key = settings.langfuse_public_key
        secret_key = settings.langfuse_secret_key
        base_url = (
            settings.langfuse_base_url
            or os.getenv("LANGFUSE_BASE_URL")
            or "https://cloud.langfuse.com"
        ).rstrip("/")
        auth = base64.b64encode(
            f"{public_key}:{secret_key}".encode("utf-8")
        ).decode("ascii")
        timeout_val = float(os.getenv("LANGFUSE_TIMEOUT", "10"))
        client_options["span_exporter"] = OTLPSpanExporter(
            endpoint=f"{base_url}/api/public/otel/v1/traces",
            headers={
                "Authorization": f"Basic {auth}",
                "x-langfuse-sdk-name": "python",
                "x-langfuse-sdk-version": langfuse_version,
                "x-langfuse-public-key": public_key,
            },
            timeout=timeout_val,
            session=create_session(),
        )
        logger.warning(
            "Langfuse TLS certificate verification is disabled for local development"
        )

    client = Langfuse(**client_options)

    if not client.auth_check():
        raise RuntimeError("Langfuse authentication failed")

    logger.info(
        "langfuse_initialized insecure_ssl=%s",
        insecure_ssl,
    )

    return client


@asynccontextmanager
async def lifespan(app: FastAPI):
    langfuse = initialize_langfuse()
    try:
        for hook in extensions.STARTUP_HOOKS:
            result = hook(app)
            if hasattr(result, "__await__"):
                await result
        logger.info("app_startup_complete")
        yield
    finally:
        for hook in extensions.SHUTDOWN_HOOKS:
            try:
                result = hook(app)
                if hasattr(result, "__await__"):
                    await result
            except Exception:
                logger.exception("app_shutdown_hook_failed")
        try:
            langfuse.shutdown()
        except Exception:
            logger.exception("langfuse_shutdown_failed")
        logger.info("app_shutdown_complete")


def create_app() -> FastAPI:
    configure_logging()
    settings = get_settings()
    app = FastAPI(title=settings.app_name, version="0.1.0", lifespan=lifespan)

    extensions.install_middleware(app)
    extensions.install_exception_handlers(app)

    for router in _BASE_ROUTERS:
        app.include_router(router)
    # Extra routers contributed by verticals via the extension seam.
    for router in extensions.ROUTERS:
        app.include_router(router)

    return app


app = create_app()
