"""add_policy_document_text_and_chunk_metadata

Revision ID: 0225224feefc
Revises: h3c4d5e6f7g8
Create Date: 2026-08-10 16:19:49.089440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0225224feefc'
down_revision: Union[str, Sequence[str], None] = 'h3c4d5e6f7g8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_events_trace_created'), table_name='agent_events')
    op.drop_index(op.f('ix_chat_messages_session_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_interaction_events_user_session_created'), table_name='interaction_events')
    op.alter_column('market_trending_dishes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_menu_items_merchant_price'), table_name='menu_items')
    op.alter_column('merchant_complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_merchant_complaints_merchant_category_date'), table_name='merchant_complaints')
    op.alter_column('merchant_dimension_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_dimension_evidence_merchant_dimension'), table_name='merchant_dimension_evidence')
    op.alter_column('merchant_ratings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('merchants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_merchants_city_cuisine'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_lat_lng'), table_name='merchants')
    op.alter_column('operational_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('policy_document_chunks', sa.Column('section_title', sa.String(), nullable=True))
    op.add_column('policy_document_chunks', sa.Column('section_level', sa.Integer(), nullable=True))
    op.add_column('policy_document_chunks', sa.Column('token_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('policy_documents', sa.Column('document_text', sa.Text(), server_default='', nullable=False))
    op.drop_index(op.f('ix_pref_events_user_status_created'), table_name='preference_events')
    op.drop_index(op.f('ix_reviews_merchant_created'), table_name='reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reviews_merchant_created'), 'reviews', ['merchant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_pref_events_user_status_created'), 'preference_events', ['user_id', 'status', 'created_at'], unique=False)
    op.drop_column('policy_documents', 'document_text')
    op.drop_column('policy_document_chunks', 'token_count')
    op.drop_column('policy_document_chunks', 'section_level')
    op.drop_column('policy_document_chunks', 'section_title')
    op.alter_column('operational_metrics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_merchants_lat_lng'), 'merchants', ['lat', 'lng'], unique=False)
    op.create_index(op.f('ix_merchants_city_cuisine'), 'merchants', ['city', 'cuisine'], unique=False)
    op.alter_column('merchants', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('merchant_ratings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_dimension_evidence_merchant_dimension'), 'merchant_dimension_evidence', ['merchant_id', 'dimension'], unique=False)
    op.alter_column('merchant_dimension_evidence', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_merchant_complaints_merchant_category_date'), 'merchant_complaints', ['merchant_id', 'category', 'occurred_on'], unique=False)
    op.alter_column('merchant_complaints', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_menu_items_merchant_price'), 'menu_items', ['merchant_id', 'price'], unique=False)
    op.alter_column('market_trending_dishes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_interaction_events_user_session_created'), 'interaction_events', ['user_id', 'session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_timestamp'), 'chat_messages', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_agent_events_trace_created'), 'agent_events', ['trace_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
