"""Remove agent traces table (use langfuse instead)

Revision ID: 2c8b142d873c
Revises: 0225224feefc
Create Date: 2026-08-12 12:25:39.385011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c8b142d873c'
down_revision: Union[str, Sequence[str], None] = '0225224feefc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_agent_events_trace_semantic_seq'), table_name='agent_events', postgresql_where='(seq IS NOT NULL)')
    op.drop_table('agent_events')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('trace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crew_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('intent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('token_usage_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('trace_id', name=op.f('agent_runs_pkey'))
    )
    op.create_table('agent_events',
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trace_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parent_event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('task_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('input_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('output_summary_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('error_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('seq', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('span_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parent_span_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kind', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('actor_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('actor_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('debug_payload_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['agent_runs.trace_id'], name=op.f('agent_events_trace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('agent_events_pkey'))
    )
    op.create_index(op.f('uq_agent_events_trace_semantic_seq'), 'agent_events', ['trace_id', 'seq'], unique=True, postgresql_where='(seq IS NOT NULL)')
    # ### end Alembic commands ###
